### ISSUE TITLE
python version >= 3.6

### ISSUE THREAD

**Issue by PicoJr** [bouttier/mvim#8]
Hello,

> Use format strings instead of % syntax
commit: 776d0e12ae28da6ae060531fb3bdc7b337110a33

requires python **\>=3.6** as stated here: <https://www.python.org/dev/peps/pep-0498/>

Maybe it is worth adding to the README?

Best regards,

PicoJr.

**Comment by bouttier** [comment]
Done in 32a8ea503512afa6a641872a5a22b1ddbda4f0e4
